#!/bin/bash
pdftk elliptic_curve_dev.pdf cat 11-13 output PRFC_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 14-18 output ABTB_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 19-28 output CH01_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 29-29 output PT01_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 30-41 output CH02_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 42-58 output CH03_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 59-75 output CH04_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 76-87 output CH05_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 88-99 output CH06_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 100-102 output PT02_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 103-109 output CH07_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 110-121 output CH08_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 122-128 output CH09_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 129-140 output CH10_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 141-147 output CH11_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 148-163 output CH12_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 164-166 output PT03_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 167-185 output CH13_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 186-211 output CH14_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 212-224 output CH15_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 225-235 output CH16_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 236-245 output CH17_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 246-282 output CH18_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 283-323 output CH19_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 324-327 output APXA_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 328-331 output APXB_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 332-335 output APXC_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 1-2 output TCBF_rosing2_elliptic_curve_dev.pdf
pdftk elliptic_curve_dev.pdf cat 3-9 output TOC_rosing2_elliptic_curve_dev.pdf
